# Enable Pyflakes and pycodestyle rules.
lint.select = ["E", "F"]

# Never enforce `E501` (line length violations). E402:Module level import not at top of file
lint.ignore = ["E501", "E402","F403","F405"]

# Always autofix, but never try to fix `F401` (unused imports).
fix = true
lint.unfixable = ["F401"]

# Ignore 
[lint.per-file-ignores]
